{{- if eq (include "yr-k8s.anyCoreComponentEnabled" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yr-k8s.fullname" . }}-runtime
  namespace: {{ include "yr-k8s.namespace" . }}
  labels:
    {{- include "yr-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  s3-access-key: {{ .Values.global.secrets.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.global.secrets.s3SecretKey | quote }}
  curve-secret: {{ .Values.global.secrets.curveSecret | quote }}
{{- end }}
