ARG BASE_IMAGE=yr-base
FROM ${BASE_IMAGE}

COPY openyuanrong_sdk*.whl /tmp/
RUN pip install --no-cache-dir /tmp/openyuanrong_sdk*.whl && \
    python_bin_dir="$(python -c 'import sysconfig; print(sysconfig.get_path("scripts"))')" && \
    test -x "${python_bin_dir}/yrcli" && \
    ln -sf "${python_bin_dir}/yrcli" /usr/local/bin/yrcli && \
    rm -f /tmp/openyuanrong_sdk*.whl

WORKDIR /root
