export YR_SERVER_ADDRESS="172.18.0.4:8888"
export YR_METASERVICE_ADDRESS="172.18.0.4:31111"
export YR_SERVER_NAME="test"
export YR_ENABLE_FRONTEND_TLS="true"
export YR_PRIVATE_KEY_FILE="/home/wyc/code/openyuanrong/cert/yr/module.key"
export YR_CERT_FILE="/home/wyc/code/openyuanrong/cert/yr/module.crt"
export YR_VERIFY_FILE="/home/wyc/code/openyuanrong/cert/yr/ca.crt"
export YR_IN_CLUSTER="false"
