# Buildkite Pipeline - Standard SSH Mode

env:
  BUILD_ARCH: "amd64"
  BUILDER_IMAGE: "swr.cn-southwest-2.myhuaweicloud.com/yuanrong-dev/compile-ubuntu2004:v20260409_guaranteed"

steps:
  - label: ":key: Initialize and Load"
    command: |
      bash .buildkite/pipeline.dynamic.yml | buildkite-agent pipeline upload
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: "swr.cn-southwest-2.myhuaweicloud.com/yuanrong-dev/compile-ubuntu2004:v20260409_guaranteed"
                resources:
                  limits: { cpu: "4", memory: "8Gi" }
    agents:
      queue: "default"
      arch: "amd64"
