{{- if .Values.etcd.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "yr-k8s.etcdServiceName" . }}
  namespace: {{ include "yr-k8s.namespace" . }}
  labels:
    {{- include "yr-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
    app: {{ include "yr-k8s.etcdServiceName" . }}
spec:
  serviceName: {{ include "yr-k8s.etcdServiceName" . }}
  replicas: {{ .Values.etcd.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: etcd
  template:
    metadata:
      labels:
        {{- include "yr-k8s.labels" . | nindent 8 }}
        app.kubernetes.io/component: etcd
        app: {{ include "yr-k8s.etcdServiceName" . }}
    spec:
      containers:
        - name: etcd
          image: {{ include "yr-k8s.image" (dict "root" . "image" .Values.etcd.image) }}
          imagePullPolicy: {{ .Values.etcd.image.pullPolicy }}
          command:
            - /usr/local/bin/etcd
          args:
            - --name=etcd0
            - --data-dir={{ .Values.etcd.dataDir }}
            - --listen-client-urls=http://0.0.0.0:{{ .Values.etcd.service.port }}
            - --advertise-client-urls=http://{{ include "yr-k8s.etcdAddrList" . }}
          ports:
            - name: client
              containerPort: {{ .Values.etcd.service.port }}
              protocol: TCP
{{- with .Values.etcd.probes.readiness }}
          readinessProbe:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.etcd.probes.liveness }}
          livenessProbe:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.etcd.resources }}
          resources:
{{ toYaml . | nindent 12 }}
{{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.etcd.dataDir }}
      volumes:
{{- if .Values.etcd.persistence.enabled }}
        []
{{- else }}
        - name: data
          emptyDir: {}
{{- end }}
{{- if .Values.etcd.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
{{ toYaml .Values.etcd.persistence.accessModes | nindent 10 }}
{{- with .Values.etcd.persistence.storageClassName }}
        storageClassName: {{ . | quote }}
{{- end }}
        resources:
          requests:
            storage: {{ .Values.etcd.persistence.size }}
{{- end }}
{{- end }}
