{{- if and .Values.master.enabled .Values.master.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yr-k8s.serviceAccountName" (dict "root" . "component" "master" "values" .Values.master) }}
  namespace: {{ include "yr-k8s.namespace" . }}
  labels:
    {{- include "yr-k8s.labels" . | nindent 4 }}
{{- end }}
