{{- if and .Values.node.enabled .Values.node.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yr-k8s.serviceAccountName" (dict "root" . "component" "node" "values" .Values.node) }}
  namespace: {{ include "yr-k8s.namespace" . }}
  labels:
    {{- include "yr-k8s.labels" . | nindent 4 }}
{{- end }}
