appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = postgres
dataSourceName = user=casdoor password=casdoor_password host=casdoor-db port=5432 sslmode=disable dbname=casdoor
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isDemoMode = false
batchSize = 100
ldapServer =
ldapPort =
ldapBaseDn =
ldapAdminDn =
ldapAdminPassword =
ldapUserFilter =
ldapGroupFilter =
ldapGroupBaseDn =
ldapGroupMemberAttribute =
ldapGroupMemberFormat =
ldapIdAttribute =
origin = "http://wyc.pc:18888"
staticBaseUrl = "https://cdn.casbin.org"
initDataFile = "./init_data.json"
frontendBaseUrl = "http://wyc.pc:18888"
verificationCodeTimeout = 5
