global:
  namespace:
    name: yr
  cluster:
    name: yr
    region: dev
    azId: local-dev-az1
  imageRegistry: localhost:5000
  images:
    master:
      tag: local
    frontend:
      tag: local
    node:
      tag: local
    traefik:
      tag: local
  externalEtcd:
    addrList: yr-etcd.yr.svc.cluster.local:2379
    metaStoreAddress: http://yr-etcd.yr.svc.cluster.local:2379

traefik:
  service:
    type: LoadBalancer
    annotations:
      kubernetes.io/elb.class: union
      kubernetes.io/elb.autocreate: '{"type":"public","bandwidth_name":"yr-traefik-elb","bandwidth_chargemode":"traffic","bandwidth_sharetype":"PER","bandwidth_size":5,"eip_type":"5_bgp"}'

frontend:
  service:
    type: LoadBalancer
    annotations:
      kubernetes.io/elb.class: union
      kubernetes.io/elb.autocreate: '{"type":"public","bandwidth_name":"yr-frontend-elb","bandwidth_chargemode":"traffic","bandwidth_sharetype":"PER","bandwidth_size":5,"eip_type":"5_bgp"}'
