services:
  traefik:
    image: ghcr.io/traefik/traefik:v3.6.10
    container_name: yr-traefik
    ports:
      - "18888:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./cert:/etc/traefik/cert:ro
      - traefik-logs:/var/log/traefik
    networks:
      - yr-net
    restart: unless-stopped

volumes:
  traefik-logs:

networks:
  yr-net:
    external: true
