tls:
  certificates:
    - certFile: /openyuanrong/cert/module.crt
      keyFile: /openyuanrong/cert/module.key

http:
  routers:
    redirect-to-https:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      middlewares:
        - https-redirect
      service: noop@internal

    frontend-root:
      entryPoints:
        - web
      rule: "Path(`/`)"
      service: frontend
      tls: {}

    frontend-terminal:
      entryPoints:
        - web
      rule: "PathPrefix(`/terminal`) || PathPrefix(`/api/instances`) || PathPrefix(`/api/jobs`) || PathPrefix(`/api/sandbox`) || PathPrefix(`/functions`) || PathPrefix(`/api-docs`) || PathPrefix(`/admin/v1/functions`) || PathPrefix(`/serverless/v1/functions`) || PathPrefix(`/serverless/v1/stream`) || PathPrefix(`/serverless/v1/componentshealth`) || PathPrefix(`/serverless/v1/posix`) || PathPrefix(`/frontend/v1/instance`) || PathPrefix(`/datasystem/v1`) || PathPrefix(`/serverless/v2`) || PathPrefix(`/app/v1`) || PathPrefix(`/client/v1/lease`) || PathPrefix(`/invocations`) || Path(`/healthz`)"
      service: frontend
      tls: {}

  middlewares:
    https-redirect:
      redirectRegex:
        regex: "^http://([^/]+)(/.*)?$"
        replacement: "https://${1}${2}"
        permanent: true

  services:
    frontend:
      loadBalancer:
        serversTransport: frontend-transport
        servers:
          - url: "https://__AIO_NODE_IP__:8889"

  serversTransports:
    frontend-transport:
      insecureSkipVerify: true
